name: hw-parser
version: '0.1.0.0'
synopsis: Simple parser support
description: Please see README.md
category: Data, Parser
author: John Ky
maintainer: newhoggy@gmail.com
copyright: 2016-2018 John Ky
license: BSD3
github: haskell-works/hw-parser
homepage: http://github.com/haskell-works/hw-parser#readme
extra-source-files:
- README.md

ghc-options:
- -Wall

dependencies:
- base          >= 4          && < 5
- attoparsec    >= 0.13       && < 0.14
- bytestring    >= 0.10       && < 0.11
- hw-prim       >= 0.4        && < 0.7
- text

library:
  source-dirs: src
  exposed-modules:
  - HaskellWorks.Data.Parser
